Pre-generate uuid for swap (jsc#SLE-17081)
yast/yast-storage-ng pull request #1192
Opened 2020-12-18 16:04 UTC by ancorgs

## Problem

*Short description of the original problem.*

- *Bugzilla link*
- *openQA link*
- *Links to other related pull requests*

## Solution

*Short description of the fix.*

## Testing

- *Added a new unit test*
- *Tested manually*

## Screenshots

*If the fix affects the UI attach some screenshots here.*

2020-12-21 09:48 UTC, dgdavid approved these changes

2020-12-21 10:45 UTC, dgdavid approved these changes
Before merging it, we need to bump the version and update the changelog

2020-12-21 10:45 UTC, dgdavid requested changes
Before merging it, we need to bump the version and update the changelog

2020-12-21 12:27 UTC, dgdavid commented
I tested it using a minimal profile for SLE Desktop and it seems to work as expected:

![Screenshot_sle15sp3-2_2020-12-21_12:26:08](https://user-images.githubusercontent.com/1691872/102777099-d948b980-4387-11eb-8673-6ffad5623d30.png)

2020-12-21 16:19 UTC, imobachgs approved these changes

2020-12-22 09:06 UTC, dgdavid commented
When (re)using an encrypted swap, it still using the device name.

![Screenshot_sle15sp3-2_2020-12-22_09:01:30](https://user-images.githubusercontent.com/1691872/102870422-e8397580-4434-11eb-90bb-b98e7bfc04db.png)

2020-12-22 09:40 UTC, dgdavid approved these changes

2020-12-22 09:41 UTC, merged