ensure no install media are mounted when storage proposal is run (bsc#1196061)
yast/yast-storage-ng pull request #1288
Opened 2022-03-09 17:20 UTC by wfeldt

## Problem

- https://bugzilla.suse.com/show_bug.cgi?id=1196061
- https://trello.com/c/bC5yVZas

When the installation repository is on some local disk partition and the partition is included in the storage setup, the existing mountpoints will lead to confusion.

libstorage-ng

- has problems with existing mountpoints in probing data that no longer exist in the commit phase
- mixes up mountpoints as it does not know the difference between installation system (no prefix) and target system (`/mnt` prefix)
- may show popups and/or remove the mountpoint from the target system's fstab

## Solution

To avoid this, unmount all installation media before probing.

## See also

- https://github.com/openSUSE/linuxrc/issues/288

2022-03-10 10:27 UTC, lslezak approved these changes
From the package manager POV LGTM

2022-03-10 10:27 UTC, lslezak commented
I'm just not sure about that reprobing, that's for some storage experts...

2022-03-10 11:00 UTC, wfeldt commented
This is a valid point but I didn't find a better solution.

The original probing happens in the middle of some really complex workflow (with add-ons, roles, full and online workflow) and it would make sense to not do it there at all but we need the storage data for other things. And also I'm not that sure what happens if we detach the repos at that point.

And even if we detach the repos at the first probing point people can still go for explicit reprobing in the expert partitioner and then we're in this mess again unless we at least detach the repos *again* at the proposal stage.

So I'd leave the first probing where it is to generate some storage data for whatever it is needed and at the proposal point detach the repo and probe again to get the state we need later at the commit phase.

2022-03-11 09:37 UTC, ancorgs commented
Reprobing also invalidates the staging devicegraph, throwing away all the changes done by the proposal or manually with the Expert Partitioner. And that reprobing would be silently executed every time we reach this point in the workflow. No matter if we are going forward or backwards.

I feel is too risky.

2022-03-11 09:45 UTC, ancorgs requested changes
As written in my previous comment, I fair this would have too many side effects in cases that currently work. Is a too big change to be done under the hood.

2022-03-11 09:52 UTC, wfeldt commented
That leaves:

(1)
 - ensure media are detached when we do the original probing and
 - ensure media are detached at the proposal stage by reviewing our workflow

or (2)

- add a dedicated client that just does the media detaching and reprobing and insert it before the proposal; but that might raise issues as our workflow is highly configurable

2022-03-31 15:13 UTC, closed without merging